# -*- coding: utf-8 -*-
"""stock_predictor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IHWQjR3FeXlRmKpBxcy1yYWZ80cWWYo2
"""

#libraries imported
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

#data collected into variables
start = '2013-01-01'
end = '2023-01-01'
boeing_stock = 'BA'

prices = yf.download(boeing_stock, start, end)

#visualization of data
prices

#remove null values
prices.dropna(inplace=True)

training_data = pd.DataFrame(prices.Close[0: int(len(prices)*0.80)])
testing_data = pd.DataFrame(prices.Close[int(len(prices)*0.80): len(prices)])

training_data.shape[0]
testing_data.shape[0]


prices.drop(['level_0'], axis=1)


prices.head()


#rolling average of stock prices
average = prices.Close.rolling(100).mean()
