# -*- coding: utf-8 -*-
"""stock_predictor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IHWQjR3FeXlRmKpBxcy1yYWZ80cWWYo2
"""

#libraries imported
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

#data collected into variables
start = '2013-01-01'
end = '2023-01-01'
boeing_stock = 'BA'

prices = yf.download(boeing_stock, start, end)

#visualization of data
prices

